version: "3.8"

services:
  network-test:
    image: ghcr.io/warklot/network-test:v1
    container_name: network-test
    restart: unless-stopped
    ports:
      - "5001:5000"
    security_opt:
      - seccomp:unconfined
