name: Setup Python, Build Image, Push Image.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run basic syntax test
        run: python -m py_compile *.py 

      - name: Testing Ping functionality
        run: python -m pytest tests/test_ping.py

      - name: Build Docker image
        run: docker build -t network-test:latest .

      - name: Log in to GHCR
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Tag Docker image
        run: |
          docker tag network-test:latest ghcr.io/${{ secrets.DOCKER_USERNAME }}/network-test:latest
          docker tag network-test:latest ghcr.io/${{ secrets.DOCKER_USERNAME}}/network-test:v1

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME}}/network-test:latest
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME}}/network-test:v1
