name: Setup Python, Build Image, Push Image.

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run basic syntax test
        run: python -m py_compile *.py 

      - name: Testing Ping functionality
        run: python -m pytest tests/test_ping.py -vv -s

      - name: Log in to GHCR
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image (ARM64 for Pi)
        run: |
          docker build --platform linux/arm/v8 -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/network-test:v1 .


      - name: Set up SSH for Ansible
        uses: webfactory/ssh-agent@v0.8.2
        with:
          ssh-private-key: ${{ secrets.RASPBERRY_SSH_KEY }}

          
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Deploy via Ansible
        run: ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
