name: CI/CD for Network Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest


    # Clone repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      ## Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install Python dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run syntax check on Python files
      - name: Run basic syntax test
        run: python -m py_compile *.py 

      # Run unit tests
      - name: Run unit tests
        run: python -m pytest tests/test_ping.py -vv -s

      # Add Raspberry Pi to SSH known hosts
      - name: Add Raspberry Pi to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 78.58.109.113 >> ~/.ssh/known_hosts

      # Set up QEMU for ARM32 emulation-
      - name: Set up QEMU (for ARM emulation)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


      # Export Docker credentials as environment variables for Ansible
      - name: Build and push multi-arch Docker image
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/network-test:v1 \
            --push .  


      # EXPORT for usage later in ansible
      - name: Export Docker credentials for Ansible
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV

      # Set up SSH agent with Raspberry Pi private key
      - name: Set up SSH for Ansible
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.RASPBERRY_SSH_KEY }}

      # Install Ansible on runner
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # Deploy application to Raspberry Pi using Ansible
      - name: Deploy via Ansible
        run: ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
