name: CI/CD for Network Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest


    #----------get code AKA CLONE-----------------------------
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #----------SETUP PYTHON----------------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      #----------INSTALL LIBRARIES FROM REQUIREMENTS-----------
      - name: Install dependencies
        run: pip install -r requirements.txt

      #-----TESTS----------------------------------------------
      - name: Run basic syntax test
        run: python -m py_compile *.py 
      - name: Run unit tests
        run: python -m pytest tests/test_ping.py -vv -s

      #-----ADD RAPSBERY----------------------------------------------
      - name: Add Raspberry Pi to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 78.58.109.113 >> ~/.ssh/known_hosts

      #-----SETUP TO FOR DOCKER----------------------------------------------
      - name: Set up QEMU (for ARM emulation)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      #-----SETUP DOCKER FOR ARM64----------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #-----LOGIN TO GITHUB CONTAINER REGISTRY----------------------------------------------
      - name: Log in to GHCR
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


      #-----BUILD AND PUSH IT TO GITHUB CONTAINER REGISTRY----------------------------------------------
      - name: Build and push ARM64 Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/network-test:v1 \
            --push .

      # EXPORT for usage later in ansible
      - name: Export Docker credentials for Ansible
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV

      #-----LOGIN TO RASPBERRY PI----------------------------------------------
      - name: Set up SSH for Ansible
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.RASPBERRY_SSH_KEY }}

      #-----INSTALL ANSIBLE----------------------------------------------
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      #-----RUN ANSIBLE ON RASPBERRY TO DEPLOY---------------------------------
      - name: Deploy via Ansible
        run: ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
